### ISSUE TITLE
Group Chats cause crash with Prosody

### ISSUE THREAD

**Issue by RussellAult** [ZeWaren/jabber-hangouts-transport#3]
Prosody has an in-built check that only allows components to send messages from their own JID. Since both the single chat and group chat sides of this component share a transport, Prosody only sees the component as hangups.example.net, and any messages from conf.hangups.example.net cause Prosody to send an error, close the connection to the component, and log a warning. This, in turn, produces an InvalidFrom error in the transport's XMPP library and causes the component itself to crash.

I see only two possibly solutions: creating and using a separate transport for group chat, or using only a single JID for both components. I'm currently attempting the former on my fork, but it doesn't yet work (since there isn't yet any logic in jh_xmpp.py to only send messages from the correct transport).

**Comment by RussellAult** [comment]
It turns out there's actually a third way: I altered the jh_xmpp.py transport to use two separate connections. I haven't submitted a pull request because I'm not certain yet that the code actually works (although it does seem to be working for me), but you can see my changes if you compare the master branch of my fork with the main project's: https://github.com/ZeWaren/jabber-hangouts-transport/compare/master...RussellAult:master

**Comment by ZeWaren** [comment]
Did you ask Prosody's dev team? Maybe they're aware of this problem and have a solution.

If they don't, I'll gladly accept your changes.

I've never used Prosody before, but it's my understanding that it is widely used. Thus, I want the transport to work with it.

**Comment by RussellAult** [comment]
With Prosody, the error I was receiving seems to be very intentional. At line 208 of the [code for the component interface](https://github.com/bjc/prosody/blob/master/plugins/mod_component.lua#L208) it does a search to see if the component's JID and the domain of the sending address (for messages coming from the component destined for Prosody user accounts) match, and if they don't, it throws the error I was receiving. According to that, the only way for your component to send messages from both hangups.example.net and conf.hangups.example.net to Prosody is to make your component look like two separate components with two separate XMPP connections, one for each domain, which is what I've attempted in my fork.

As for accepting my changes, the reason I didn't both even submitting a pull request is that this is literally the first Python code I've ever looked at, to say nothing of my unfamiliarity with the XMPP or Hangups libraries. The changes I made seem to be working for me, but that's as far as I'll vouch for them. If you look at my code and like what you see, please feel free to pull it into your project, but I won't swear that it's good, or even well-written...

**Comment by ZeWaren** [comment]
In the same file, we can see that this domain verification is optional:
https://github.com/bjc/prosody/blob/master/plugins/mod_component.lua#L206

It can be disabled with a param:
https://github.com/bjc/prosody/blob/master/plugins/mod_component.lua#L92

Can you try setting `validate_from_addresses` to `false` in your config file?

Maybe that would be the easiest solution.

**Comment by RussellAult** [comment]
Good find on the totally-undocumented option!

Unfortunately, it's only a half-fix: the component no longer crashes (since Prosody is no longer forcibly closing the connection), but conf.hangups.example.net now throws "Service unavailable" errors in my client any time I try to access it (e.g. for a room list, or to open a conversation). It appears that Prosody is only willing to send component traffic to conf.hangups.example.net if there is actually a component connected to it with that JID, and without that connection it reports conf.hangups.example.net as being offline. By splitting the connections, conferencing was working perfectly for me.

**Comment by jprjr** [comment]
Just thought I'd throw a thought into the mix - I've been trying out spectrum2, they do groupchats and direct messaging on one JID. I think using a single JID is a good idea.

**Comment by ZeWaren** [comment]
I've actually been thinking the same thing.
That would be the simplest option.
I'll get to it as soon as I find time to reopen the project.

**Comment by ZeWaren** [comment]
I moved everything into the main JID.

You can see the changes in commit 8d1845db356c6361fe34b59a8648976a219f3732.

I'm going to test that in the next few days, and if everything goes well I'll merge into master and make a new release.

**Comment by ZeWaren** [comment]
Done. Now the transport uses a single JIDs to connect to the server.
