### ISSUE TITLE
Remove pydevd dependency

### ISSUE THREAD

**Issue by RussellAult** [ZeWaren/jabber-hangouts-transport#4]
When the component is started, the first thing it does is call `setup_debugging()` which, among other things, imports pydevd. I don't have pydevd on my XMPP server, so I commented out the `setup_debugging()` call. I'm sure there's a more elegant way to do this, but it did remove the dependency and allow the software to run. For a non-Python-developer like me, running without pydevd is practically a necessity. Is there a better way to remove this dependency, or at least make it optional? Thanks!

**Comment by ZeWaren** [comment]
Oops, that code wasn't supposed to reach `master`.
I've removed it.
