### ISSUE TITLE
Wrong message timestamps in groupchats history

### ISSUE THREAD

**Issue by diggit** [ZeWaren/jabber-hangouts-transport#7]
Timestamps of all groupchat messages loaded from server are incorrect. All messages downloaded from server has same timestamp, time when they were downloaded from server.
One bad effect is, that some clients(conversations) evaluates them as new and fires up notifications.

My setup is ejabberd 15.07.6, upstream jabber-hangouts-transport. Tested with Gajim and 
Comversations clients.
Which debug option log would help to find problem?

**Comment by paullouisageneau** [comment]
I encounter the same problem, and I'd be happy to help debugging.
My setup is Prosody 0.9.7 with jabber-hangouts-transport branch jid-merge and Conversations client.

**Comment by ZeWaren** [comment]
I just tried both Gajim and Conversations.

I'm running ejabberd-14.07_2.

**In conversation:**
Do you mean that when you open a group chat and the latest 50 messages are downloaded, they show as being posted "just now"?

This shouldn't happen. The transport send these messages with a delay, as specified in:
http://xmpp.org/extensions/xep-0045.html#enter-history

Example:

```
<message from="all_me@hangouts.enceinte.tf/Erwan Martin" type="groupchat" id="40847" to="zewaren@enceinte.tf/phone">
  <body>Jambon</body>
  <delay xmlns="urn:xmpp:delay" from="all_me@hangouts.enceinte.tf" stamp="2016-06-15T16:33:34.968451+00:00" />
</message>
```

I'm going to have a look at Conversations' source code and check this out, and maybe open a ticket there if they're at fault.

**In Gajim:**
I didn't see any timestamp problem.
Can you describe the bug in more details?

**Comment by diggit** [comment]
> In **conversation:**
> Do you mean that when you open a group chat and the latest 50 messages are downloaded, they show as being posted "just now"?

 Yes. I had to disable notification for groupchats, because history is re-downloaded on every reconnection and it happens a lot on mobile network. (eg.: in subway and so...)
This seems to be problem with Conversations, Gajim handles these messages like history and does not fire up any notification.

> In **Gajim:**
> I didn't see any timestamp problem.
> Can you describe the bug in more details?

It is not such problem, just time/date information of all messages get lost. You can't know if last message is 1 min or 1 week old. Sometimes, this kind of info comes handy.

This is example from Gajim after joining groupchat.

```
You are now known as ‎Me
‎[12:08:55 PM] ‎A: text of message...
‎[12:08:55 PM] ‎B: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
‎[12:08:55 PM] ‎B: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
‎[12:08:55 PM] ‎B: text of message...
‎[12:08:55 PM] ‎A: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
‎[12:08:55 PM] ‎A: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
‎[12:08:55 PM] ‎Me‎: text of message...
```

...one more thing
**Presence in groupchats**
This is problem too, all contacts are seen as available. This does not match contact status in roster which is corect.

**Comment by diggit** [comment]
Probably as consequence, gajim keeps renaming groupchat to same name on each start. This annoys other users on hangouts. It could be problem with gajim which does not expect such timestamps.
