### ISSUE TITLE
Prosody configuration

### ISSUE THREAD

**Issue by diggit** [ZeWaren/jabber-hangouts-transport#8]
Hi,
I am unable to configure transport to fully work with prosody.
My current prosody config part with Component settings:

```
Component "hangups.myhost.me"
        component_secret = "mypass"

Component "conf.hangups.myhost.me"
        component_secret = "mypass"
```

I set transport to work on port 5347 which is default for prosody external components.

Normal chat works, but conferences not. Once I try to so something with conferences on client side, transport fails with:

```
...
Stanza name:  presence
Stanza name:  presence
Stanza name:  presence
[]
Stanza name:  error
[(<class 'xmpp.protocol.InvalidFrom'>, InvalidFrom(('invalid-from', 'Component tried to send from address <conf.hangups.myhost.me> which is not in domain <hangups.myhost.me>'),), <traceback object at 0x7fec4431a5c8>)]
```

And stops working. Transport restart is necessary.

I guess prosody is confused with 2 external components on 1 port.
Does anybody have working config with prosody? Any ideas how to fix this?

**Comment by diggit** [comment]
Oh, I found explanation. Prosody uses [XEP-114](https://xmpp.org/extensions/xep-0114.html) to connect external components. On the other hand this transport uses [XEP-225](https://xmpp.org/extensions/xep-0225.html) which adds [several features like multiple hostnames per stream](https://xmpp.org/extensions/xep-0225.html#intro).

Maybe I can start two separate instances, one for muc and one for normal chat. Workaround, but idk about better solution. This requires everything duplicated :/

**Comment by diggit** [comment]
It is not possible to start transport with <confjid> only, without <jid>. So no separate instance for conferences transport :(

**Comment by ZeWaren** [comment]
Hey,
There's a branch in the code called jid-merge, which fixes that problem by merging the conf JID and the main JID into a single one.
There was no actual reason to have them split that way (the example I used as my base did so I did).
I'll merge this into master when I find some time.

**Comment by ZeWaren** [comment]
Done. Can you get the latest version and try your configuration again?

**Comment by diggit** [comment]
Thanks! Everything looks to be working.
I am using Gajim as client and registering procedure is closest to Pidgin. You have to add **conf@** manually in front of jid to list groupchats.

Yes, this was duplicate of #3
